<%@ Page Title="" Language="C#" MasterPageFile="~/Page/FrontEnd.Master" AutoEventWireup="true" CodeBehind="Home4FrontEnd.aspx.cs" Inherits="QuanLyGiaoVien.Page.Home4FrontEnd" %>

<asp:Content ID="Content2" ContentPlaceHolderID="main_body" runat="server">
     <p style="text-align:center ;font-weight:bold; text-decoration:none">KHOA CÔNG NGHỆ THÔNG TIN – ĐH CÔNG NGHIỆP HÀ NỘI</p>
     <p style="text-align:center ;font-weight:bold; text-decoration:none">MỘT ĐỊA CHỈ ĐÀO TẠO NHÂN LỰC CNTT ĐƯỢC DOANH NGHIỆP TIN CẬY</p><br />
    <p>Đào tạo gắn liền với thực tiễn chính là chìa khóa nâng cao chất lượng nguồn nhân lực CNTT. Khoa CNTT trường ĐH Công nghiệp Hà Nội chính là một địa chỉ đào tạo nhân lực ngành CNTT được doanh nghiệp tin cậy</p><br />
    <p>Theo dữ liệu được Công ty tuyển dụng trực tuyến VietnamWorks công bố (tổng hợp xuyên suốt năm 2015), số lượng việc làm nhóm ngành công nghệ thông tin (CNTT) tăng 47% mỗi năm nhưng lượng nhân lực của ngành chỉ tăng trưởng ở mức 8%. </p><br />
    <p>Theo Sách trắng CNTT Việt Nam 2014, ước tính đến năm 2020, Việt Nam cần khoảng một triệu lao động ngành CNTT, nhưng hiện tổng số nhân lực làm việc trong ngành này mới đạt hơn 440.000 người, trong đó kỹ thuật Phần mềm là ngành có nhu cầu nhân lực cao nhất trong khối ngành CNTT. Theo báo cáo của Gartner (công ty nghiên cứu và tư vấn hàng đầu về công nghệ thông tin) Việt Nam hiện nằm trong top 10 nước hàng đầu tại châu Á - Thái Bình Dương và 30 của thế giới về gia công và phát triển phần mềm. Trong năm 2014, TP.HCM xếp thứ 7 và Hà Nội xếp thứ 22 trong tốp 100 thành phố hấp dẫn về gia công phần mềm. Từ năm 2012, Việt Nam trở thành đối tác gia công phần mềm lớn thứ 2 của Nhật Bản. Những năm gần đây, ngành công nghệ thông tin luôn phát triển với tốc độ cao (năm 2013 tăng 55,3% so với năm 2012) khiến cho nhu cầu về nhân lực trong lĩnh vực này cũng tăng cao</p><br />
     <p style="text-align:center"><img src="../Images/trangchu4.JPG" width="350" height="auto"   /></p><br />
    <p>Một trong số nội dung được triển khai, áp dụng đó là đổi mới chương trình đào tạo, thay đổi phương pháp đào tạo, đưa sinh viên tiếp cận sớm với doanh nghiệp ngay từ khi còn ngồi trên ghế nhà trường, rất nhiều hình thức hướng nghiệp cho sinh viên như: Tổ chức hội thảo, thăm quan doanh nghiệp, mời doanh nghiệp tham gia vào các sân chơi, chương trình lớn; tuyển dụng thực tập sinh viên vào các kỳ thực tập và làm đồ án. Từ đó kết quả sinh viên ra trường đã được nhiều doanh nghiệp tiếp nhận.
Theo Báo cáo về Tình hình việc làm sinh viên tốt nghiệp năm 2016, tỷ lệ sinh viên tốt nghiệp có việc làm ngành HTTT đạt 98%, ngành KHMT đạt 92.9%, ngành KTPM đạt 90.4%, ngành CĐ CNTT đạt 89%.</p><br />
    <p>Với sự phát triển vượt bậc như vậy, Công nghệ thông tin trong đời sống văn hóa, xã hội, giáo dục, kinh tế và thời đại ngày nay có tầm ảnh hưởng, tác động rất lớn đến sự phát triển, ổn định của các doanh nghiệp và của mỗi quốc gia nói chung, Việt Nam nói riêng trong giai đoạn hiện nay cũng như trong tương lai. Khoa CNTT trường ĐH Công nghiệp Hà Nội dần khẳng định được vị thế của mình trong việc đào tạo và cung cấp nguồn nhân lực CNTT cho xã hội.</p>
</asp:Content>
